# Generated by Django 5.0.1 on 2024-02-03 04:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_id', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('coupon_code', models.CharField(max_length=50)),
                ('issuer', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prev_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64)),
                ('nonce', models.IntegerField()),
                ('transactions', models.ManyToManyField(to='blockchain.transaction')),
            ],
        ),
    ]
