# Generated by Django 5.0.1 on 2024-02-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_wallet_transaction_amount_transaction_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='offer_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
