# Generated by Django 5.0.1 on 2024-02-03 18:35

import blockchain.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_alter_wallet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='user_id',
            new_name='issuer_id',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.CharField(default=blockchain.models.generate_wallet_address, editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
