# Generated by Django 5.0.1 on 2024-02-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0006_alter_wallet_issuer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='state',
        ),
        migrations.AddField(
            model_name='transaction',
            name='on_chain',
            field=models.BooleanField(default=False),
        ),
    ]
