# Generated by Django 5.0.1 on 2024-02-04 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0008_wallet_is_linked_wallet_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_wallet', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_paper_wallets', to='blockchain.wallet')),
            ],
        ),
    ]
